### PR TITLE
handling error escape xml

### PR DESCRIPTION
**Pull request by ans-4175**
I've made changes so it would resolve this [issue](https://github.com/rubenv/node-xlsx-writer/issues/10). Already passed test on Grunt

### CODE REVIEW

**Comment by rubenv** [comment]
Could you add a unit test to describe what this fixes?

It should fail without the patch. This way we're sure that any future changes won't break this again.

**Comment by ans-4175** [comment]
there's no need for another test case, your test cases already covered it all.

**Comment by rubenv** [comment]
Then why do we need this patch?

**Comment by ans-4175** [comment]
I've got an error, said that
```
/works/nolimit/cql-hit/node_modules/xlsx-writer/lib/index.js:224
    return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt
               ^
TypeError: Object 5 has no method 'replace'
at XlsxWriter.escapeXml (/works/nolimit/cql-hit/node_modules/xlsx-writer/lib/index.js:224:16)
    at /works/nolimit/cql-hit/node_modules/xlsx-writer/lib/index.js:134:45
    at /works/nolimit/cql-hit/node_modules/xlsx-writer/node_modules/async/lib/async.js:551:21
    at /works/nolimit/cql-hit/node_modules/xlsx-writer/node_modules/async/lib/async.js:227:13
    at iterate (/works/nolimit/cql-hit/node_modules/xlsx-writer/node_modules/async/lib/async.js:134:13)
    at /works/nolimit/cql-hit/node_modules/xlsx-writer/node_modules/async/lib/async.js:145:25
    at /works/nolimit/cql-hit/node_modules/xlsx-writer/node_modules/async/lib/async.js:229:17
    at WriteStream.<anonymous> (/works/nolimit/cql-hit/node_modules/xlsx-writer/node_modules/async/lib/async.js:556:34)
    at WriteStream.g (events.js:180:16)
    at WriteStream.emit (events.js:117:20)
```
Here's one element of my array's object
```
{
    	original_id:"656258342147502080",
    	content:"RT @GingerLanier: Putin and the Shiite 'Axis of Resistance' http://t.co/eumnAIIrTV",
    	date_created:"2015-10-19 23:59:16",
    	from_display_picture:"http://pbs.twimg.com/profile_images/651504414998396928/hdoQSqiv_400x400.jpg",
    	from_id:"308130306",
    	from_name:"Novorossiyan",
    	url:"http://twitter.com/statuses/656258342147502080",
    	sentiment:5,
    	score:0,
    	social_media:"Twitter",
    	score_breakdown:[],
    	"extra":[]
    }
```
So whats your idea?

**Comment by ans-4175** [comment]
After that error I made a quickfix in `lib/index.js` as in prev issue (that's how I solved my problem).
Then I forked your repo, make some changes.
Could you just merge my unit test, `object_test.coffee` then see by yourself ?

**Comment by rubenv** [comment]
Ok, now I see it. This is very strange, there's numeric_test which does seem to work without problems.

Need to look into this. Thanks for the test.

**Comment by ans-4175** [comment]
Same for me, that's strange after I saw your repo..hehe
Thanks again

**Comment by rubenv** [comment]
Stuff has come up so I don't really have the time to dive into this, but I guess it can't hurt if things work for you.

Release 0.0.11 with this fix, thanks!

**Pull request merged**
